# Generated by Django 3.2.13 on 2022-06-28 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmwatchcount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmgroup',
            name='FilmGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filmwatchcount.filmgroup'),
        ),
    ]
