# Generated by Django 3.2.13 on 2022-06-30 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmwatchcount', '0002_filmgroup_filmgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='FilmGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filmwatchcount.filmgroup'),
        ),
        migrations.AlterField(
            model_name='filmgroup',
            name='FilmGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filmwatchcount.filmgroup'),
        ),
    ]
