# Generated by Django 3.2.13 on 2022-07-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmwatchcount', '0003_auto_20220630_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwatch',
            name='DateWatched',
            field=models.DateField(verbose_name='Date watched'),
        ),
    ]
