# Generated by Django 3.2.13 on 2022-07-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_film_releaseyear'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['Name', 'ReleaseYear']},
        ),
        migrations.AlterModelOptions(
            name='filmgroup',
            options={'ordering': ['Name']},
        ),
        migrations.AlterField(
            model_name='film',
            name='ReleaseYear',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Release year'),
        ),
        migrations.AlterField(
            model_name='filmwatch',
            name='DateWatched',
            field=models.DateField(blank=True, verbose_name='Date watched'),
        ),
        migrations.AlterField(
            model_name='filmwatch',
            name='Notes',
            field=models.TextField(blank=True),
        ),
    ]
