# Generated by Django 3.2.13 on 2022-07-07 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_filmwatch_datewatched'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmwatch',
            options={'verbose_name_plural': 'Film watches'},
        ),
        migrations.AlterField(
            model_name='film',
            name='FilmGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.filmgroup', verbose_name='Film group'),
        ),
        migrations.AlterField(
            model_name='film',
            name='Name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='filmgroup',
            name='FilmGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.filmgroup', verbose_name='Film group'),
        ),
        migrations.AlterField(
            model_name='filmgroup',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
