# Generated by Django 3.2.13 on 2022-07-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20220707_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='ReleaseYear',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Release year'),
        ),
    ]
